create table authorities (username integer not null, authority integer not null, primary key (username, authority)) engine=InnoDB;
create table tbl_address (id_address integer not null auto_increment, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null, external_number varchar(5) not null, internal_number varchar(5), references_street varchar(128), street varchar(50) not null, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, zip_code varchar(50) not null, primary key (id_address)) engine=InnoDB;
create table tbl_characters (id_character integer not null auto_increment, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null, description varchar(60), icon varchar(150) not null, name varchar(20) not null, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, primary key (id_character)) engine=InnoDB;
create table tbl_colors (id_color integer not null auto_increment, hex_code varchar(10) not null, name varchar(20) not null, primary key (id_color)) engine=InnoDB;
create table tbl_donations (id_donation integer not null auto_increment, authorization TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null, is_completed TINYINT default 0 not null, quantity double(10,2) not null, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, user_id integer not null, primary key (id_donation)) engine=InnoDB;
create table tbl_favorites_pets (id_pet integer not null, id_user integer not null) engine=InnoDB;
create table tbl_logs (id_log integer not null auto_increment, action enum ('Crear', 'Actualizar', 'Eliminar') not null, board enum ('address', 'characters', 'colors', 'donations', 'favorites_pets', 'logs','news', 'pets', 'pets_adopted', 'pet_images', 'profile', 'request','roles', 'sizes', 'tags', 'tags_news','types', 'users', ) not null, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null, new_data TEXT not null, old_data TEXT not null, user_id integer, primary key (id_log)) engine=InnoDB;
create table tbl_news (id_news integer not null auto_increment, content LONGTEXT not null, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null, image varchar(250), is_main tinyint default 0 not null, is_published tinyint default 1 not null, title varchar(50) not null, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, user_id integer, primary key (id_news)) engine=InnoDB;
create table tbl_pets (id_pet integer not null auto_increment, age enum ('Cachorro/Cria', 'Joven', 'Adulto') default 'Cachorro/Cria', breed varchar(60), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null, gender tinyint not null, is_active tinyint default 0 not null, is_adopted tinyint default 0 not null, name varchar(30) not null, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, character_id integer, color_id integer, size_id integer, type_id integer, user_id integer, primary key (id_pet)) engine=InnoDB;
create table tbl_pets_adopted (id_pet_adopted integer not null auto_increment, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null, is_canceled tinyint default 0 not null, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, pet_id integer, user_id integer, primary key (id_pet_adopted)) engine=InnoDB;
create table tbl_pets_images (id_sizes integer not null auto_increment, image varchar(150) not null, pet_id integer, primary key (id_sizes)) engine=InnoDB;
create table tbl_profiles (id_profile integer not null auto_increment, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null, image varchar(150), last_name varchar(50) not null, name varchar(50) not null, phone varchar(17), second_name varchar(50), updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, address_id integer not null, user_id integer not null, primary key (id_profile)) engine=InnoDB;
create table tbl_requests (id_request integer not null auto_increment, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null, is_accepted tinyint default 0 not null, reason varchar(140) not null, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, user_id integer not null, primary key (id_request)) engine=InnoDB;
create table tbl_roles (id_role integer not null auto_increment, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null, description varchar(50), type varchar(20) not null, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, primary key (id_role)) engine=InnoDB;
create table tbl_roles_users (role_id_role integer not null, users_id_user integer not null) engine=InnoDB;
create table tbl_sizes (id_size integer not null auto_increment, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null, name varchar(30) not null, size_range varchar(30) not null, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, primary key (id_size)) engine=InnoDB;
create table tbl_tags (id_tag integer not null auto_increment, description varchar(50), name varchar(20) not null, primary key (id_tag)) engine=InnoDB;
create table tbl_tags_news (id_news integer not null, id_tag integer not null) engine=InnoDB;
create table tbl_types (id_type integer not null auto_increment, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null, description varchar(60), name varchar(20) not null, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, primary key (id_type)) engine=InnoDB;
create table tbl_users (id_user integer not null auto_increment, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null, email varchar(50) not null, is_active tinyint default 1 not null, link_restore_password varchar(150), password varchar(50) not null, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, primary key (id_user)) engine=InnoDB;
alter table tbl_characters add constraint UK_73fy7ne7hj759lml5nlleapdm unique (name);
alter table tbl_colors add constraint UK_cl0m1h7nej9n6fqucekk29a43 unique (name);
alter table tbl_profiles add constraint UK_fm7ttmtghdxiswllxq92bd21h unique (address_id);
alter table tbl_profiles add constraint UK_rl45kcltkwt9n7v5q7g1mqys1 unique (user_id);
alter table tbl_requests add constraint UK_9bler7hojqyae3vq8gta8i55i unique (user_id);
alter table tbl_roles add constraint UK_a1xpul9ew944uva4eapf2junk unique (type);
alter table tbl_sizes add constraint UK_ir8y5ewdf2jvj4jhpdui9kwom unique (name);
alter table tbl_tags add constraint UK_5xuyx2anqogugpxo2nh5rcdi6 unique (name);
alter table tbl_types add constraint UK_nxi3fmjy44rvrugy8q8pcujbq unique (name);
alter table tbl_users add constraint UK_j562wwmipqt96rkoqbo0jc34 unique (email);
alter table authorities add constraint FKdoibywymbmr1dpvjvrs5f1nsw foreign key (authority) references tbl_roles (id_role);
alter table authorities add constraint FKpjy4ndmuy6qnikmdutbth8r0h foreign key (username) references tbl_users (id_user);
alter table tbl_donations add constraint FKm2wocagr804egk23vxx92saua foreign key (user_id) references tbl_users (id_user);
alter table tbl_favorites_pets add constraint FK94ek01nylg9xfd7ov8qsfapt6 foreign key (id_user) references tbl_pets (id_pet);
alter table tbl_favorites_pets add constraint FKo1mn5jtbs3gpgt9udf2r5f1xv foreign key (id_pet) references tbl_users (id_user);
alter table tbl_logs add constraint FK65mksvw9u07744kud5ew8ixo9 foreign key (user_id) references tbl_users (id_user);
alter table tbl_news add constraint FKi4kuq9i7l8x00mkt04x3bpw6k foreign key (user_id) references tbl_users (id_user);
alter table tbl_pets add constraint FKkiuc03x30r5n8sgeorrw3tock foreign key (character_id) references tbl_characters (id_character);
alter table tbl_pets add constraint FK7s53uiseg1n92xfk31gasba2e foreign key (color_id) references tbl_colors (id_color);
alter table tbl_pets add constraint FKfj2uil18yaobslcrd6h1sn4u7 foreign key (size_id) references tbl_sizes (id_size);
alter table tbl_pets add constraint FK22grkemc6n0jn42lhbashd8xx foreign key (type_id) references tbl_types (id_type);
alter table tbl_pets add constraint FKikyti9nbq8xitbyn1gvlw9nk foreign key (user_id) references tbl_users (id_user);
alter table tbl_pets_adopted add constraint FKlh4md07puh6vr83ch87uui6bl foreign key (pet_id) references tbl_pets (id_pet);
alter table tbl_pets_adopted add constraint FKmy2rysktdi6eykh3rkmog5wqt foreign key (user_id) references tbl_users (id_user);
alter table tbl_pets_images add constraint FKgloq3koek0qyiyxdddv95pb2t foreign key (pet_id) references tbl_pets (id_pet);
alter table tbl_profiles add constraint FK4l18w8nb2bw6ss52uj05sgnqx foreign key (address_id) references tbl_address (id_address);
alter table tbl_profiles add constraint FK82ah1u8uxt6gwicd1carp78aa foreign key (user_id) references tbl_users (id_user);
alter table tbl_requests add constraint FKgxrr5w4fcie3cnogrlmspnud8 foreign key (user_id) references tbl_users (id_user);
alter table tbl_roles_users add constraint FK4s65k9xdxe8xbdljut8wnga77 foreign key (users_id_user) references tbl_users (id_user);
alter table tbl_roles_users add constraint FKkgplm167c62eyv8qqpmlxta6j foreign key (role_id_role) references tbl_roles (id_role);
alter table tbl_tags_news add constraint FKojp27rfbt5b57u2bkkgdtbaq4 foreign key (id_tag) references tbl_tags (id_tag);
alter table tbl_tags_news add constraint FK7vjuch8sfo0ua3otetdfha0js foreign key (id_news) references tbl_news (id_news);
